spring.application.name=ceylon_vistas

#DB Configurations
spring.datasource.url=jdbc:mysql://localhost:3306/ceylon_vistas
spring.datasource.username=root
spring.datasource.password=1234

#JPA Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true